
language: node_js
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mongodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mongodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p /data/db; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mongod; fi

node_js:
  - "10"
services:
  - mongodb
  - docker
