
language: node_js
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
before_install:
  - docker pull mongo
  - docker run -p 27017:27017 -d mongo
  - docker pull eclipse-mosquitto
  - docker run -p 1883:1883 -p 9001:9001 -d eclipse-mosquitto
node_js:
  - "10"
services:
  - docker
