
language: node_js
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker docker-compose docker-machine xhyve docker-machine-driver-xhyve; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then docker-machine create default --driver xhyve --xhyve-experimental-nfs-share; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval $(docker-machine env default); fi
  - docker pull mongo
  - docker run -p 27017:27017 -d mongo
  - docker pull eclipse-mosquitto
  - docker run -p 1883:1883 -p 9001:9001 -d eclipse-mosquitto

node_js:
  - "10"
services:
  - docker
