
language: node_js
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mongodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p /data/db; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mongod; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -E apt-add-repository -y "ppa:mosquitto-dev/mosquitto-ppa"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -E apt-get -yq update &>> ~/apt-get-update.log; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install mosquitto; fi

node_js:
  - "10"
services:
  - mongodb
