version: '0.0.1'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb_data:/var/db
  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"

